### ISSUE TITLE
Getting an error message when running vagrant up on the advanced installation

### ISSUE THREAD

**Issue by Hanan100** [imduffy15/devcloud4#10]
I was able to get the advanced installation up without any issue after setting the appropriate chef version but I had to get a new clean install I got the following error message. 

==> management: Recipe Compile Error
==> management: ================================================================================
==> management: 
==> management: 
==> management: Chef::Exceptions::RecipeNotFound
==> management: --------------------------------
==> management: could not find recipe client for cookbook mysql
==> management: 
==> management: 
==> management: [2015-01-01T09:01:24+00:00] ERROR: Running exception handlers
==> management: [2015-01-01T09:01:24+00:00] ERROR: Exception handlers complete
==> management: [2015-01-01T09:01:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> management: [2015-01-01T09:01:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by Hanan100** [comment]
The issue is still occurring when running vagrant up  in the advanced file (Not the binary installation advanced). 

There are no recipes available for mysql server or client in the cookbooks. I checked the following folder : devcloud4-master/common/management/cookbooks/mysql

**Comment by imduffy15** [comment]
I've been unable to recreate this.... Can you delete ~/.berkshelf and retry?

**Comment by Hanan100** [comment]
I have deleted ~/.berkshelf but still get the following error message

==> management: Recipe Compile Error
==> management: ================================================================================
==> management: 
==> management: Chef::Exceptions::RecipeNotFound
==> management: --------------------------------
==> management: could not find recipe client for cookbook mysql
==> management: 
==> management: [2015-01-13T18:02:10+00:00] ERROR: Running exception handlers
==> management: [2015-01-13T18:02:10+00:00] ERROR: Exception handlers complete
==> management: [2015-01-13T18:02:10+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> management: [2015-01-13T18:02:10+00:00] ERROR: could not find recipe client for cookbook mysql
==> management: [2015-01-13T18:02:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.


Similarly There are no recipes available for mysql server or client in the cookbooks. I checked the following folder : devcloud4-master/common/management/cookbooks/mysql

**Comment by imduffy15** [comment]
I've tried to recreate this and have been unable to do so.... I even started off with a completely clean machine installed vagrant vagrant-berkshelf and chefdk. Everything went smoothly.

I am unable to recreate your issue and I have no idea what is causing it. updated the vagrantfile to use a specific version of chef.... this may or may not help, I'm unsure.

`common/management/cookbooks/mysql` is no longer used, this was in the past when the project used chef librarian for cookbook dependency management.

**Comment by imduffy15** [comment]
With #11 closed; how is this issue? can it remain closed/solved?

**Comment by Hanan100** [comment]
I am not getting this error message anymore after the updates you have made so lets consider it closed/sloved
